import datetime
raw_data_filter = [
  {'archive': False,
   'authorDisplayName': 'BatmanShampoo',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 16, 16, 33),
   'commentID': 25863,
   'down_vote': None,
   'fanID': 3896,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwDyt4r0JGdXMdPYnGaXTwnUEkKtB8_Zxjiog=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Amazing video as always! Keep up the awesome work bringing '
                  'laughs and smiles!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Lukas van der Heul',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 12, 14, 24),
   'commentID': 25877,
   'down_vote': None,
   'fanID': 14733,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwXeAzbLHuG_I_R8flkD3VGm7OTBYKncPjJ2tv9rw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'BOOM! Another cool video of Matt Mulholland has arived in my '
                  'subscribsion list! Love It!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'P Elnerud',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 12, 2, 22, 33, 24),
   'commentID': 25839,
   'down_vote': None,
   'fanID': 4045,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzreDMwlepx-hd2mU5f4FCqT7Iall-AJoloA-9c=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Yesss!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'David Lang',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 10, 21, 14),
   'commentID': 25933,
   'down_vote': None,
   'fanID': 3974,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzvOmnTsA91zWviyECT-sft2g_WlxThvvLP_m1oNuc=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Delightful!  Tasty Bones!',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Junkmech',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 19, 27, 40),
   'commentID': 25858,
   'down_vote': None,
   'fanID': 14141,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJymZVZeOBTgKkSaRTWFlQBw6nGuHgWE1HkmekCvww=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Let the panties hit the floor.',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'gml4',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 17, 6, 20),
   'commentID': 25926,
   'down_vote': None,
   'fanID': 13065,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJx4rJMozMawnopW_TwtW0d9YZ5f-551Xyh0Dw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Wait a minute... I can only like this once?! This made me '
                  'super happy to see you working with my favorite youtube '
                  'trombonist... great collaboration. This one completely '
                  'justifies my opinion that you are a very talented musician '
                  'Matt.... thank you for sharing this, and all that you do.',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'mynameismatt2010',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 12, 1, 1, 6, 46),
   'commentID': 25846,
   'down_vote': None,
   'fanID': 12780,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJz90VfgUZwHDDtihzUX_yTWMYdSf_dIx3O5Rw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "Awesome as always Matt! I'm wondering if you're planning on "
                  'continuing to move more towards these more serious covers or '
                  'if there will be more comedy videos to come? Either way your '
                  'videos are always great!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Michelle Karbon',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 19, 2, 1),
   'commentID': 25859,
   'down_vote': None,
   'fanID': 3945,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwgwf9bW8WM46uEg8ECRCuDD18Is4usviCrZCHv3g=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "You're so awesome! I love this and we need another recorder "
                  'by candlelight soon!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Brigitta Sz.',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 25, 6, 53, 34),
   'commentID': 25916,
   'down_vote': None,
   'fanID': 13453,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJyVben0E203Z_mgaX3OJ1s2QNgp3u5QcG21S_l2Jg=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Még mindig szuper hangod van :) jó lett a klip! BYEEEEEE XD',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'shikumaru55',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 11, 23, 13),
   'commentID': 25930,
   'down_vote': None,
   'fanID': 13747,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJxnXmg4gIIRFy0PYKwS-Eb2400IR8Vwaj0Oow=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "So you're not dead?",
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'TayR0C',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 11, 41, 11),
   'commentID': 25886,
   'down_vote': None,
   'fanID': 3812,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJz1XSafI6rgc5U0LlI_7uLIHarmX-tFigimYM4z=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'You going to make another awesome christmas video this year?',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Tom Brehm',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 21, 28, 13),
   'commentID': 25922,
   'down_vote': None,
   'fanID': 13445,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzqNwFCa4kkqGc_Ea3RZYVc5AYonyqPeHJ5Ztuw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'favorite!',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Jacana',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 12, 43, 22),
   'commentID': 25875,
   'down_vote': None,
   'fanID': 3797,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzzA74xHrEr3_CmK9OPlpWxGrSlnz8RwOdJSQ=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "Love this. 'My Girl' is the first song ever did an "
                  'arrangement of, and I love your take on it.',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Finlay Craig',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 13, 11, 52),
   'commentID': 25873,
   'down_vote': None,
   'fanID': 13378,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwnMSdvt_a_9Kxj16LiONQZHCKQxjAAw8rbLEFPWQ=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'can i be one of your ladies?',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Mr Humpty',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 15, 14, 43),
   'commentID': 25865,
   'down_vote': None,
   'fanID': 13588,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzwtG4vBk2YoPvCd5O3TQSmxiol1L-82jCFmw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Another patreon payment well spent. Keep up the great work.\n'
                  '\n'
                  '/hattip',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Fury',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 19, 51, 29),
   'commentID': 25923,
   'down_vote': None,
   'fanID': 13773,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJxlcONeKie3r0QaOeawZhfiCFHVOopOeSt9Ii8SjSc=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "Yus another video I'm gonna go and eat popcorn and watch "
                  'this .... Your awesome man',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Kevin Smith',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 12, 1, 13, 43, 28),
   'commentID': 25842,
   'down_vote': None,
   'fanID': 13534,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwy0gR2DInZqsUnyb4IH__iu3v-HuVkXmdgZJV6tw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Nice work.\xa0 Very different from the original.\xa0 I like '
                  'the jazz-like feel it has.\xa0 Any chance of a cover of '
                  "Stevie Wonder's My Cherie Amour?",
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Rose Broussard',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 23, 52, 28),
   'commentID': 25848,
   'down_vote': None,
   'fanID': 13093,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJw30JAfkHBSGdSBUHxcqHg_vLQmrgT3qFz3JItra3w=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'I love the ending',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Junkmech',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 19, 30, 44),
   'commentID': 25857,
   'down_vote': None,
   'fanID': 14141,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJymZVZeOBTgKkSaRTWFlQBw6nGuHgWE1HkmekCvww=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Wait why did you trim your beard?',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'robkiddmusic',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 12, 1, 23, 38, 10),
   'commentID': 25841,
   'down_vote': None,
   'fanID': 13495,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzGl_IHDB0c5sN4aq4Yympb_WPTb7mjP66DYEfA=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Awesome job man, as always!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Adam Duskett',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 5, 13, 54, 38),
   'commentID': 25903,
   'down_vote': None,
   'fanID': 14806,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzO6PAC7r11s8xy2h5UYWMudPpAxPtk5sBAZZC9wg=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Matt; I have been watching your youtube videos for a few '
                  "years now; and I haven't found a single bad video yet.\n"
                  'May I make the suggestion of doing a CCR song?',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Trett Films',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 21, 1, 47),
   'commentID': 25855,
   'down_vote': None,
   'fanID': 13451,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwyLWim4Y8Da4Qiz1Jr8hXSChvCV37oGfihL6EIjw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Fit',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'DreamBig vake',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 12, 5, 14, 59, 44),
   'commentID': 25835,
   'down_vote': None,
   'fanID': 14802,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzklg2l5m197CAZjTaP4BcVCvXIXMur7BhmjB68=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "Hey Matt not sure if you've ever done this or ever "
                  'considered this but you should do tutorials on how to play '
                  'songs like this and others, you would have a lot more '
                  'content and it would be pretty awesome dude',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Yatsey',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 16, 19, 17),
   'commentID': 25862,
   'down_vote': None,
   'fanID': 13687,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJx-uK_PCPT4ADq9lJ7X6cAGLQhHFP2nxgi9sw=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Is it weird to be a male heterosexual, but yet turned on?',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'citruscyanide',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 26, 10, 52, 52),
   'commentID': 25913,
   'down_vote': None,
   'fanID': 13670,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJy-xS5PL2dhbQb0sAd56_uDCK9uDBHjN6d3ag=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Wow.',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'gnarleypunkroker5',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 25, 4, 47, 13),
   'commentID': 25917,
   'down_vote': None,
   'fanID': 13997,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwr1DRATwT3xmr-zqrtGIU8n180zoc_o3SZjXt8=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'will you be doing another funny christmas song this year?',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'jarrett davis',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 11, 42, 50),
   'commentID': 25885,
   'down_vote': None,
   'fanID': 14920,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJyHdcilTgDkT-ffl6zUjazc3I8yuGB5kCvmtXQJ=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'love you Matt.',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Guz Man',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 25, 0, 36, 43),
   'commentID': 25919,
   'down_vote': None,
   'fanID': 14682,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwCb8fgmIUQXSWerefUHoHKKQ_GmXvMC1LRaUaJ=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Finally something new!!',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Atahan Özaydın',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 13, 21, 17),
   'commentID': 25872,
   'down_vote': None,
   'fanID': 15102,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwejQql2bpbguiWx7GrxTEtb__JMNkIOKn9J2ia8A=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'i kinda started to miss the immature and awkward stuff like '
                  '"accidental incest" or "sort your shit out". Great cover '
                  'though...',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Austin Judicpa',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 11, 45, 43),
   'commentID': 25882,
   'down_vote': None,
   'fanID': 13710,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJyRSW9mmgeI1e0sn1hSzMYBhAydCyj_m5bcpg=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Will you be doing anymore loop covers? Those are my '
                  'favorites!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Manu',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 13, 11, 56),
   'commentID': 25929,
   'down_vote': None,
   'fanID': 4114,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJyJTpITiGyNLb-gjPYu0WrnJ8drrKvW7RVssPZj=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Nice combo of sounds with the sordinoish trombone and your '
                  'voice + piano. Thanks for making this',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Aaron M',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 24, 7, 55, 54),
   'commentID': 25943,
   'down_vote': None,
   'fanID': 13703,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJziY8H9CUTXloiORwRvgJPpBf3q-W8ddPGUGg=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "Woo! I'm the king of the comments!",
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Rando Stuffington',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 10, 31, 2, 47, 47),
   'commentID': 25905,
   'down_vote': None,
   'fanID': 14626,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJzDYbO98hBU560LAnhUd2Wu59LHS_PVqXqbdCxX=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Fantastic. Happy Halloween!',
   'up_vote': None,
   'videoTitle': 'And So It Goes by Billy Joel | Matt Mulholland & Chris Bill '
                 'Cover'},
  {'archive': False,
   'authorDisplayName': 'Anders Thorsen Holm',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 22, 39, 7),
   'commentID': 25849,
   'down_vote': None,
   'fanID': 13409,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJxfRPuNdYUmtUFS5snWqEG658qA4QWejS0alg=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Looks like you really enjoyed playing this. Thanks again, '
                  "Matt - you're awesome!",
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Lucas Denny',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 21, 42, 10),
   'commentID': 25853,
   'down_vote': None,
   'fanID': 14470,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJwEh5cQBsB8i7q-gguKiDbtpJO3dL65cWD8TMd1=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'MATEE!! One of you best covers in my opinion. Love it, keep '
                  'it up Matt!',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'Pants',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 11, 30, 14, 6, 8),
   'commentID': 25868,
   'down_vote': None,
   'fanID': 13780,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJxi48FNnxfVd4kc1RGzLIHA-lHLLB-g37H8eBJ5=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': 'Got so into reading the blog that I forgot to watch the '
                  'video. Duhh.\n'
                  '\n'
                  'Anyways, sweet guitar tone.',
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
  {'archive': False,
   'authorDisplayName': 'BlueRedGooGoo',
   'badge': 'topFan',
   'commentDatePosted': datetime.datetime(2015, 12, 3, 5, 19, 51),
   'commentID': 25838,
   'down_vote': None,
   'fanID': 13857,
   'platformAvatar': 'https://yt3.ggpht.com/a/AATXAJyR-sdCNbsOvgYS1dMb3Xa__r2mZ6hXF21c1w=s48-c-k-c0xffffffff-no-rj-mo',
   'textDisplay': "I'm not even gay, but here I am, in love with this man,",
   'up_vote': None,
   'videoTitle': 'My Girl | The Temptations | Matt Mulholland Cover'},
 ]