import datetime
raw_data_f = [
 {'badge': 'topFan',
  'displayName': 'Taquam34',
  'fanID': 4039,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 1, 21, 5, 4, 10),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwGuTRmWQ5LvMWsepBODQIGkVZ0qjzwtwfpdg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'mynameismatt2010',
  'fanID': 12780,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 10, 17, 3, 31, 41),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJz90VfgUZwHDDtihzUX_yTWMYdSf_dIx3O5Rw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'citruscyanide',
  'fanID': 13670,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 3, 3, 22, 11, 11),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJy-xS5PL2dhbQb0sAd56_uDCK9uDBHjN6d3ag=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Axel Werner',
  'fanID': 3804,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 11, 25, 6, 59, 26),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzzQ2Axg918nYIBtjNBuNK93UETSh8Y46wq5ZqkSa8=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'P Elnerud',
  'fanID': 4045,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2015, 12, 2, 22, 33, 24),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzreDMwlepx-hd2mU5f4FCqT7Iall-AJoloA-9c=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Chris Winters',
  'fanID': 3782,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 4, 21, 10, 12, 46),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzpmQp695gPpl60QmFlWQx5pYzoBHjb1bXulnvz=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Casey Watson',
  'fanID': 3808,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 7, 11, 23, 0, 57),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx0yWybRSyYMIaMEC6bN6fXT1StboCO1aWOUe_Jug=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'arky3000',
  'fanID': 3981,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 4, 21, 13, 5, 9),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJy36CZQt7PUE6tG2z5DuCXekAGUzXFuBoFJaK6p=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Adri Elric',
  'fanID': 3878,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 3, 11, 23, 15, 26),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJywsMeRklCDRnJLWB9j013qXbQ1KVsIDNxA4Y5d=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Joshua Taylor',
  'fanID': 3980,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 12, 14, 9, 2, 32),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxYSUhMDwZayt2GTT0fR0oK67674tqzsL3jCw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Kate F',
  'fanID': 13068,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 17, 3, 9, 39),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwznuF4TbjitXlPgzXX1XWG2bnPl0GvvlohUCsZKg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'russtuff',
  'fanID': 13552,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 1, 20, 18, 38, 17),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx7zvbDlFg44-79bDrn0kvmglC2ILJzqsMudsJD=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'BNJMN',
  'fanID': 3989,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 3, 29, 10, 5, 56),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJweNeJeFCvzrAK4273H0_tTtGi8CX3_ST6SRlq1cw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'TayR0C',
  'fanID': 3812,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 10, 17, 8, 46, 58),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJz1XSafI6rgc5U0LlI_7uLIHarmX-tFigimYM4z=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Darklycopene',
  'fanID': 3949,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 11, 2, 53, 30),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx3fJ6qVZH67a9wmuLF0sFgMq-SPo7smkC5Riwe=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'AlbatraozProductions',
  'fanID': 3960,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 17, 1, 12),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxmM4-R03E73idnJ-GScRIAUhTXBQg_7u5F71o4wg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Agustín Pinar',
  'fanID': 13866,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 4, 2, 15, 41, 56),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyQOHpJqWAM0bsggH_Ko9GL3KJIRA2MhMX-2bvQjg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Jacob the Wells',
  'fanID': 13892,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 6, 2, 0, 28, 27),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyAl9PNCfEZza9EkFP7tw6eckBmDh27T_V0q1uK=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Sammikins',
  'fanID': 13106,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 11, 3, 8, 4, 28),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyvVP-TOvaYTiIq6dMmEveRCOYaewgEqlMMgkip3g=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'BlackAdder665',
  'fanID': 13105,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 25, 21, 23, 55),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx6ZBtrxMN_-DVZtQHyiazdKV40jhysGiM20g=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'internallogic',
  'fanID': 12972,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 6, 3, 6, 31, 7),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxMz_S4Y3VrdP2Z4Og8oXUJomX4wUsv2C2PioY1=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'DreamBig vake',
  'fanID': 14802,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 1, 23, 11, 56, 57),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzklg2l5m197CAZjTaP4BcVCvXIXMur7BhmjB68=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'ILSBConcept',
  'fanID': 12862,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 7, 11, 23, 4, 50),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJw4rQZzuksTq7KZ6an74z10Ci7HWG0SGU8mtxlGjg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Edward',
  'fanID': 13540,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 1, 20, 18, 54, 25),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJw027ot22bIjT168DH97w5iGqgHYEb2jUnRvQGskw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'JoeBlu',
  'fanID': 3915,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 9, 18, 5, 40, 34),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxvrokB9cHvdM4rkq7bMUCQ1PsUwkKm0e1Ta98jWA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Klampfe',
  'fanID': 3876,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 5, 20, 12, 34, 4),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyLNf2F3X8UnZBsnNFTTfdT6ycl072_nFLyrA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'beavinator1',
  'fanID': 4066,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 17, 4, 28, 32),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxGakETe6hvOZi9m8iDNcp_uaWY2Y7eOTYtqKW-=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Carter F',
  'fanID': 14204,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 24, 21, 1, 45),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwC8UZEwJ1ZX9Ghvtu4XDEn0JFB7vR-3hVdLz_NEpY=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'MrGhostlore',
  'fanID': 12960,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 25, 3, 11, 44),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyIEt4sfH2UfJ-OtHgrYAZV6gPPvC6LSFv_trg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Benjamin Richter',
  'fanID': 13553,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 5, 15, 4, 20),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx4OfF6pvYBCn7ahZOkQQ9g1uConlBIpkn0IKx2Uw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Junkmech',
  'fanID': 14141,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 5, 8, 30, 11),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJymZVZeOBTgKkSaRTWFlQBw6nGuHgWE1HkmekCvww=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'The Blazing Sloth',
  'fanID': 3952,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 4, 29, 15, 1, 39),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxVHq11QYYSUCsINC6IDNiXN823W9VWysLkVKyf=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'NeoStar',
  'fanID': 12798,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 7, 5, 13, 4, 18),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx5FfdAH5-XMq5wRa7Cp6_rT7UT9WdiLVBZ3MM=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Fury',
  'fanID': 13773,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 3, 29, 9, 52, 54),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxlcONeKie3r0QaOeawZhfiCFHVOopOeSt9Ii8SjSc=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Cipher Dec',
  'fanID': 3857,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 8, 1, 56, 8),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwNqdYdEMWqxmibmWNO2rh_i-pOKv_-CMMh3ri17g=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Finlay Craig',
  'fanID': 13378,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 5, 13, 42, 45),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwnMSdvt_a_9Kxj16LiONQZHCKQxjAAw8rbLEFPWQ=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Willow Tufts',
  'fanID': 12999,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 11, 2, 23, 53, 4),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJy87KlIqFBF7F1wqTOvMvBJh85wZ95iFZuAQdElPeU=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Team Crash and Burn',
  'fanID': 13053,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 3, 14, 27, 34),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJw-tAlpLWPn-5ICNGjeWFWi20NosQfQPOGQQLt8ew=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': '___',
  'fanID': 13461,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 3, 30, 20, 40, 27),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJw6wWw_1d0S2prGnhukkyVV9EaKJ1rIc3-4wwptJA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Nathan From the Comments Section',
  'fanID': 4112,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 9, 2, 0, 52, 34),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwCCor9_ZD-3YQgUOUaf5arKSTOGhtkL4qUTNwv=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'mcchewy87',
  'fanID': 3801,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 5, 1, 11, 10, 52),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyRO9l8kAcTy_jsHmYR3BZ5IWAqdaczPN__LkWf=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Lukas van der Heul',
  'fanID': 14733,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2015, 11, 30, 12, 14, 24),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwXeAzbLHuG_I_R8flkD3VGm7OTBYKncPjJ2tv9rw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'brassalpaca',
  'fanID': 13750,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 3, 30, 1, 11, 33),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxErx_nLAOsOSuJGXpGVbyuuOahUl8QdBVvf5YZhA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Captain Cerrius',
  'fanID': 3901,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 9, 1, 0, 49, 35),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzcimtv9UT07G5Igx3vRuIcOJ1f09kWEowPlQ=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'yamatsukami94',
  'fanID': 13885,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2015, 12, 21, 23, 40, 58),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwZPhvK1GafWoGRk77HsLywZkUkgnx_AraiMw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'gml4',
  'fanID': 13065,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 3, 17, 4, 52, 22),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx4rJMozMawnopW_TwtW0d9YZ5f-551Xyh0Dw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Brigitta Sz.',
  'fanID': 13453,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2015, 10, 25, 6, 53, 34),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyVben0E203Z_mgaX3OJ1s2QNgp3u5QcG21S_l2Jg=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'MarkProductions',
  'fanID': 12808,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 1, 26, 11, 14, 36),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwqVFE_V26Tgh1QFS-1NiRRgJDCUdw0cHIxCcOapA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Tyrog',
  'fanID': 13416,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 9, 27, 21, 31, 13),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwHra2DN7nPVkJSLozeKHJBSOcLFWc3o5IwbA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'shikumaru55',
  'fanID': 13747,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 3, 30, 4, 57, 37),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJxnXmg4gIIRFy0PYKwS-Eb2400IR8Vwaj0Oow=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Susanna Papette',
  'fanID': 13278,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 1, 11, 18, 52, 5),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJybcqZssW-GRpiKWaQKsOgeweUt2QepxjFSDh1o9g=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Tory Chinn',
  'fanID': 12966,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 11, 30, 9, 13, 19),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwRasFxryhThY14TyfsWFTPP7yf-boUHGaQpPrm8g=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Diego Lopez Presa',
  'fanID': 14013,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 2, 24, 22, 10, 22),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwK9Ozo8jkmym6wJ6qqTJ0c0qoijeTqI9Gn6SvWDw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'ltsune',
  'fanID': 3959,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 4, 29, 7, 51, 5),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwxuVloUteTalYAAvCmbNYsOdDymq22WQObG9zv=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'David Lang',
  'fanID': 3974,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2015, 10, 24, 10, 21, 14),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzvOmnTsA91zWviyECT-sft2g_WlxThvvLP_m1oNuc=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Misc Mitz',
  'fanID': 4030,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 1, 23, 20, 39, 53),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzmVLxycWL2NXgvB_apLdvi55b7AdWi7KClv2hw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'ilbanny',
  'fanID': 3879,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 5, 20, 7, 9, 25),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzriljbhapjE7Y6JkOxujt_Ua20RN-Gh7NywA=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'SPcamert',
  'fanID': 13046,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 4, 6, 8, 26, 5),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJyxD9mqEk4pGpVWA8RShfDCmu94u-QVi6tHIrQ0=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Teo Limberger',
  'fanID': 4035,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 10, 25, 13, 10, 43),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJy6YryN1SkeN7DuRSBExsMgBr8bMIBvVr813O8x-g=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Yatsey',
  'fanID': 13687,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2017, 5, 1, 8, 22, 40),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJx-uK_PCPT4ADq9lJ7X6cAGLQhHFP2nxgi9sw=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'BatmanShampoo',
  'fanID': 3896,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 5, 20, 1, 34, 53),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwDyt4r0JGdXMdPYnGaXTwnUEkKtB8_Zxjiog=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Jacana',
  'fanID': 3797,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2020, 5, 20, 1, 45, 54),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzzA74xHrEr3_CmK9OPlpWxGrSlnz8RwOdJSQ=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Yodenko',
  'fanID': 12769,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 4, 2, 16, 40, 53),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJwkbHsZYCctqIfRANrGOGrl1k_JPrQmdepbyQ=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Agustín Pinar',
  'fanID': 3907,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2019, 7, 5, 10, 57, 55),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJzyANAvA-pe5nAC8Z_8l5--FNxl6D8g_eV3jOYM=s48-c-k-c0xffffffff-no-rj-mo'},
 {'badge': 'topFan',
  'displayName': 'Kerkko',
  'fanID': 12974,
  'fanScore': 2,
  'lastCommentDate': datetime.datetime(2016, 4, 2, 9, 57, 18),
  'note': None,
  'profileImage': 'https://yt3.ggpht.com/a/AATXAJygsXQvpDjOhCcGoCiG9_PSCogJWJstLKF-c2FH=s48-c-k-c0xffffffff-no-rj-mo'},
]